defaults:
  - robot_model: franka_panda
  - robot_client: franka_sim'

setup:
  object_centers: {"HUMAN_CENTER": [0.5, -0.55, 0.9], "LAPTOP_CENTER": [-0.7929, -0.1, 0.0]}
  start: [-0.1515, -0.2002, -0.0195, -2.2691,  0.4506,  2.7031, -1.9165]
  T: 60.0
  save_dir: "/data/demonstrations/"