defaults:
  - robot_model: franka_panda
  - robot_client: franka_sim

ip: "localhost"

setup:
  object_centers: {"HUMAN_CENTER": [0.5, -0.55, 0.9], "LAPTOP_CENTER": [0.5, -0.1, 0.6]}
  start: [0.4228, 0.7944, 0.3174, -1.6417, -1.1393, 1.0788, 0.3520]
  T: 30.0
  save_dir: "/data/demonstrations"